site_name: fs.lua
site_url: https://mrentrasil.github.io/fs.lua
repo_name: MrEntrasil/fs.lua
repo_url: https://github.com/MrEntrasil/fs.lua

nav:
  - Home: home.md
  - Setup: setup.md
  - License: LICENSE.md
theme:
  name: material
  palette:
    primary: "black"
    accent: "black"

markdown_extensions:
  - admonition
  - codehilite
