site_name: fs.lua
site_url: https://mrentrasil.github.io/fs.lua/
site_description: fs support for Lua
site_author: MrEntrasil

repo_url: https://github.com/MrEntrasil/fs.lua
edit_uri: blob/master/

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  analytics: {gtag: 'G-274394082'}
  highlightjs: true
  hljs_languages:
    - yaml
    - django
    - lua

nav:
  - Home: README.md

extra_css:
  - css/extra.css

exclude_docs: |
  *.py

markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.snippets
  - pymdownx.superfences
  - callouts
  - mdx_gh_links:
      user: MrEntrasil
      repo: fs.lua
  - mkdocs-click

watch:
  - mkdocs
